function vtk_data = myvtk_read(file_name)

% open file
fid = fopen(file_name);

% vtk infomation

% # vtk DataFile Version 4.0
tline = fgetl_nonempty(fid);
if ~contains(tline,'# vtk DataFile Version','IgnoreCase',1)
  error('First line should be "# vtk DataFile Version"');
end
tmp = split(tline);
vtk_data.version = tmp{end};

% Generated by
tline = fgetl_nonempty(fid);
if ~contains(tline,'Generated by','IgnoreCase',1)
  error('Second line should be "Generated by"');
end
tmp = split(tline);
vtk_data.generator = tmp{end};

% ASCII
tline = fgetl_nonempty(fid);
if ~contains(tline,'ASCII','IgnoreCase',1)
  error('Thrid line should be "ASCII" or other format');
end
tmp = split(tline);
vtk_data.format = tmp{end};

% DATASET POLYDATA
tline = fgetl_nonempty(fid);
if ~contains(tline,'DATASET','IgnoreCase',1)
  error('Forth line should be "DATASET" or other format');
end
tmp = split(tline);
vtk_data.dataset = tmp{end};

% point coordinates
tline = fgetl_nonempty(fid);
tmp = split(tline);
num_elem = str2double(tmp{2});
num_vals = 3;

if num_elem>0
  
  % vertices
  vtk_data.points = sub_vtk_data_patch(fid,num_elem,num_vals);
  
  % element connectivities
  tline = fgetl_nonempty(fid);
  tmp = split(tline);
  num_elem = str2double(tmp{2});
  num_vals = str2double(tmp{3})/str2double(tmp{2});
  vtk_data.geometry = tmp{1};
  tmp = sub_vtk_data_patch(fid,num_elem,num_vals);
  vtk_data.connectivities = tmp(:,2:end);
  
  % other attributes
  tline = fgetl_nonempty(fid);
  tmp = split(tline);
  num_elem = str2double(tmp{end});
  
  % point data
  while ~feof(fid)
    tline = fgetl_nonempty(fid);
    tmp = split(tline);
    
    if tmp{1} == "CELL_DATA"
      num_elem = str2double(tmp{end});
      break;
    end
    
    name_attr = tmp{2};
    name_attr = regexprep(name_attr,'[[]-]','');
    disp(name_attr);
    
    if tmp{1}=="SCALARS"
      num_vals = str2double(tmp{end});
      fgetl_nonempty(fid);
    else
      num_vals = 3;
    end
    
    vtk_data.(name_attr) = sub_vtk_data_patch(fid,num_elem,num_vals);
  end
  
  % cell data
  while ~feof(fid)
    tline = fgetl_nonempty(fid);
    tmp = split(tline);
    
    name_attr = tmp{2};
    name_attr = regexprep(name_attr,'[[]-]','');
    disp(name_attr);
    
    if tmp{1}=="SCALARS"
      num_vals = str2double(tmp{end});
      fgetl_nonempty(fid);
    else
      num_vals = 3;
    end
    
    vtk_data.(name_attr) = sub_vtk_data_patch(fid,num_elem,num_vals);
  end
  
end

% close file
fclose(fid);

end
